// "use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import { AlertProvider } from "./context/AlertContext";

export const metadata: Metadata = {
  title: "Care4Kids",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
              
      <SessionProvider session={session}>
        <body className={inter.className}>
          <AlertProvider>{children}</AlertProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
